spring.application.name=brightpath
server.port=8081
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/brightpath?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:brightpath}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
app.fixed-now=${APP_FIXED_NOW:2026-03-06T16:30:00+07:00}